#include "generated_move_enum.h"
#include "pokedex.h"
#include "poke_enum.h"
#include "movedex.h"
#include "sim_utils/battle.h"
#include "sim_utils/pokegen.h"
#include <string.h>
#include <stdlib.h>

// Struct for a team member
typedef struct {
    POKEDEX_IDS id;
    MOVE_IDS moves[4];
} team_member;

// Array of sample RBY OU teams
// Each team is an array of 6 team_member structs
const team_member ou_teams[][6] = {
    {
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {SLEEP_POWDER_MOVE_ID, PSYCHIC_MOVE_ID, DOUBLE_EDGE_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ALAKAZAM, {PSYCHIC_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {CHANSEY, {ICE_BEAM_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, REFLECT_MOVE_ID, HYPER_BEAM_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, HYPER_BEAM_MOVE_ID, BLIZZARD_MOVE_ID, EARTHQUAKE_MOVE_ID}}
    },
    {
        {JYNX, {LOVELY_KISS_MOVE_ID, PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, COUNTER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, STUN_SPORE_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {CHANSEY, {SING_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, SURF_MOVE_ID, COUNTER_MOVE_ID, SELF_DESTRUCT_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {JYNX, {BLIZZARD_MOVE_ID, BODY_SLAM_MOVE_ID, LOVELY_KISS_MOVE_ID, REST_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, STUN_SPORE_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {GENGAR, {PSYCHIC_MOVE_ID, THUNDERBOLT_MOVE_ID, HYPNOSIS_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, SELF_DESTRUCT_MOVE_ID, HYPER_BEAM_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, THUNDERBOLT_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {GENGAR, {PSYCHIC_MOVE_ID, THUNDERBOLT_MOVE_ID, HYPNOSIS_MOVE_ID, EXPLOSION_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, STUN_SPORE_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {CHANSEY, {SING_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {ALAKAZAM, {PSYCHIC_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {CHANSEY, {ICE_BEAM_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, SELF_DESTRUCT_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {GENGAR, {PSYCHIC_MOVE_ID, THUNDERBOLT_MOVE_ID, HYPNOSIS_MOVE_ID, EXPLOSION_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, STUN_SPORE_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {STARMIE, {SURF_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {CHANSEY, {SING_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, HYPER_BEAM_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {ALAKAZAM, {PSYCHIC_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {SLEEP_POWDER_MOVE_ID, PSYCHIC_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {CHANSEY, {REFLECT_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, HYPER_BEAM_MOVE_ID, SELF_DESTRUCT_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {JYNX, {LOVELY_KISS_MOVE_ID, PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, REST_MOVE_ID}},
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {RHYDON, {EARTHQUAKE_MOVE_ID, BODY_SLAM_MOVE_ID, SUBSTITUTE_MOVE_ID, ROCK_SLIDE_MOVE_ID}},
        {CHANSEY, {ICE_BEAM_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, SELF_DESTRUCT_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, STUN_SPORE_MOVE_ID, MEGA_DRAIN_MOVE_ID}},
        {RHYDON, {EARTHQUAKE_MOVE_ID, BODY_SLAM_MOVE_ID, SUBSTITUTE_MOVE_ID, ROCK_SLIDE_MOVE_ID}},
        {CHANSEY, {SING_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, SELF_DESTRUCT_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {ALAKAZAM, {PSYCHIC_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, MEGA_DRAIN_MOVE_ID, EXPLOSION_MOVE_ID}},
        {GENGAR, {HYPNOSIS_MOVE_ID, PSYCHIC_MOVE_ID, THUNDERBOLT_MOVE_ID, EXPLOSION_MOVE_ID}},
        {CHANSEY, {ICE_BEAM_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, SELF_DESTRUCT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {GENGAR, {NIGHT_SHADE_MOVE_ID, THUNDERBOLT_MOVE_ID, HYPNOSIS_MOVE_ID, EXPLOSION_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, STUN_SPORE_MOVE_ID, EXPLOSION_MOVE_ID}},
        {STARMIE, {SURF_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, COUNTER_MOVE_ID, SELF_DESTRUCT_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, STUN_SPORE_MOVE_ID, EXPLOSION_MOVE_ID}},
        {ZAPDOS, {THUNDERBOLT_MOVE_ID, DRILL_PECK_MOVE_ID, THUNDER_WAVE_MOVE_ID, AGILITY_MOVE_ID}},
        {CHANSEY, {ICE_BEAM_MOVE_ID, THUNDERBOLT_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, REFLECT_MOVE_ID, REST_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    },
    {
        {STARMIE, {PSYCHIC_MOVE_ID, BLIZZARD_MOVE_ID, THUNDER_WAVE_MOVE_ID, RECOVER_MOVE_ID}},
        {EXEGGUTOR, {PSYCHIC_MOVE_ID, SLEEP_POWDER_MOVE_ID, STUN_SPORE_MOVE_ID, EXPLOSION_MOVE_ID}},
        {CLOYSTER, {BLIZZARD_MOVE_ID, CLAMP_MOVE_ID, REST_MOVE_ID, EXPLOSION_MOVE_ID}},
        {CHANSEY, {SING_MOVE_ID, SEISMIC_TOSS_MOVE_ID, THUNDER_WAVE_MOVE_ID, SOFT_BOILED_MOVE_ID}},
        {SNORLAX, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, HYPER_BEAM_MOVE_ID, SELF_DESTRUCT_MOVE_ID}},
        {TAUROS, {BODY_SLAM_MOVE_ID, EARTHQUAKE_MOVE_ID, BLIZZARD_MOVE_ID, HYPER_BEAM_MOVE_ID}}
    }
};

// Number of teams
const size_t num_ou_teams = sizeof(ou_teams) / sizeof(ou_teams[0]);

// Load a team from the ou_teams array
void load_team_from_ou(Player* p, int team_index) {
  // If team_index is negative, select a random team
  if (team_index < 0) {
    team_index = rand() % num_ou_teams;
  }

  // Load 6 pokemon for the team
  for (int i = 0; i < 6; i++) {
    load_pokemon(&p->team[i], ou_teams[team_index][i].moves, ou_teams[team_index][i].id);
  }
}


